services:
    db:
        image: mysql
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=db
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            timeout: 5s
            retries: 20

    app:
        build: .
        ports:
            - "3000:3000"
        depends_on:
            db:
                condition: service_healthy
        environment:
            - DB_HOST=db
            - PORT=3000
        command: sh -c 'until nc -zv db 3306; do echo "Waiting for MySQL to start..."; sleep 1; done; npm run server'
        volumes:
            - data:/fetched-data

volumes:
    data:
